'use client';
import Link from 'next/link';
import Navbar from '@/components/Navbar';
import { LangProvider } from '@/components/LanguageSwitcher';

export default function PrivacyPolicyPage() {
  const lastUpdated = 'April 2025';
  return (
    <LangProvider>
      <div className="min-h-screen bg-[#0d0202]">
        <Navbar />
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16">

          <div className="text-center mb-12">
            <h1 className="font-cinzel text-3xl font-bold text-[#f0c040] mb-3">Privacy Policy</h1>
            <p className="font-garamond text-sm text-[#e8d5b5]/50">Last updated: {lastUpdated}</p>
          </div>

          {[
            {
              title: '1. Introduction',
              content: `Welcome to Divya Stotram ("we", "our", or "us"). We are committed to protecting your personal information and your right to privacy. This Privacy Policy explains how we collect, use and share information about you when you visit our website at divyastotram.vercel.app (the "Site").`
            },
            {
              title: '2. Information We Collect',
              content: `We collect minimal information necessary to operate the site:\n\n• Usage Data: We use Google Analytics to collect anonymous information about how visitors use our site, including pages visited, time spent on pages, and general geographic location (country/city level only).\n\n• Contact Information: If you contact us via our contact form, we collect your name, email address, and the content of your message.\n\n• Search Queries: Anonymous search terms entered on our site may be stored to improve content.\n\nWe do not collect any sensitive personal information, financial information, or require user registration.`
            },
            {
              title: '3. How We Use Your Information',
              content: `We use the information we collect to:\n\n• Improve and optimize our website content\n• Understand which stotrams and languages are most popular\n• Respond to your messages and inquiries\n• Display relevant advertisements via Google AdSense\n• Analyze site traffic and usage patterns`
            },
            {
              title: '4. Google AdSense & Advertising',
              content: `We use Google AdSense to display advertisements on our site. Google uses cookies to serve ads based on your prior visits to our site or other sites. You may opt out of personalized advertising by visiting Google's Ads Settings at www.google.com/settings/ads.\n\nThird-party vendors, including Google, use cookies to serve ads based on your previous visits to our website. Google's use of advertising cookies enables it and its partners to serve ads based on your site visits.`
            },
            {
              title: '5. Google Analytics',
              content: `We use Google Analytics to understand how visitors interact with our website. Google Analytics uses cookies to collect anonymous traffic data. The information generated by the cookie about your use of the website is transmitted to and stored by Google. You can opt out of Google Analytics by installing the Google Analytics opt-out browser add-on at tools.google.com/dlpage/gaoptout.`
            },
            {
              title: '6. Cookies',
              content: `Our website uses cookies to enhance your experience. Cookies are small text files stored on your device. We use:\n\n• Essential cookies: Required for the site to function (language preferences)\n• Analytics cookies: Google Analytics (anonymous usage data)\n• Advertising cookies: Google AdSense (for displaying relevant ads)\n\nYou can control cookies through your browser settings. Disabling cookies may affect some site functionality.`
            },
            {
              title: '7. Third-Party Services',
              content: `Our site uses the following third-party services:\n\n• Google Analytics: For website analytics\n• Google AdSense: For advertising\n• Vercel: For website hosting\n• Firebase: For real-time visitor counting\n• YouTube: For embedded devotional music videos\n• Groq AI: For the "Ask the Pandit" chatbot feature\n\nEach third-party service has its own privacy policy governing the use of your information.`
            },
            {
              title: '8. Children\'s Privacy',
              content: `Our website is suitable for all ages, including children. We do not knowingly collect personal information from children under 13. If you believe we have inadvertently collected information from a child, please contact us immediately.`
            },
            {
              title: '9. Data Security',
              content: `We implement reasonable security measures to protect your information. However, no internet transmission is completely secure. We cannot guarantee the absolute security of information transmitted to our site.`
            },
            {
              title: '10. Your Rights',
              content: `You have the right to:\n\n• Access the personal information we hold about you\n• Request correction of inaccurate information\n• Request deletion of your information\n• Opt out of analytics and advertising cookies\n\nTo exercise any of these rights, please contact us at contact@divyastotram.com.`
            },
            {
              title: '11. Changes to This Policy',
              content: `We may update this Privacy Policy from time to time. We will notify you of any changes by updating the "Last updated" date at the top of this page. Your continued use of the site after changes constitutes acceptance of the new policy.`
            },
            {
              title: '12. Contact Us',
              content: `If you have any questions about this Privacy Policy, please contact us:\n\nEmail: contact@divyastotram.com\nWebsite: divyastotram.vercel.app\nLocation: India`
            },
          ].map((section, i) => (
            <div key={i} className="bg-gradient-to-br from-[#1a0505]/90 to-[#0d0202]/95 border border-[#c9922a]/20 rounded-xl p-7 mb-4">
              <h2 className="font-cinzel text-base font-bold text-[#f0c040] mb-3">{section.title}</h2>
              <p className="font-garamond text-base text-[#e8d5b5]/80 leading-relaxed whitespace-pre-line">{section.content}</p>
            </div>
          ))}

          <div className="text-center mt-8">
            <Link href="/" className="font-cinzel-reg text-xs tracking-widest uppercase text-[#c9922a]/50 hover:text-[#c9922a] transition-colors">
              ← Back to Stotrams
            </Link>
          </div>
        </div>
      </div>
    </LangProvider>
  );
}